name: Build frontend
on:
  push:
    branches: 
      - master
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
        with: 
          node-version: "16.x"
      - name: Change Working directory
        run: cd client
      - name: install dependencies
        run:  npm install
      - name: run build file
        run: npm run build
