name: Build frontend
on:
  push:
    branches: 
      - master
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
        with:
          script: |
            cd client
            npm install
            npm run buid
            echo "Build file excecuted"

