name: Build frontend
on:
  push:
    branches: 
      - master
jobs:
  Deploy-on-ec2-instance:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: ssh in ec2 remote server
        env:
          PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}
          HOSTNAME:  ${{ secrets.HOSTNAME }}
          USER_NAME:  ${{ secrets.USER_NAME }}
        run:  |
          ssh -i $PRIVATE_KEY "${USER_NAME}@${HOSTNAME}" -y
      - name: check in to the memories directory
        run:  |
          cd new-memories
