on:
  push:
    branches: [ master ]
jobs:

  Deploy-on-ec2-instance:

    runs-on: ubuntu-latest
    steps:
    - name: SSH Remote Commands
      uses: appleboy/ssh-action@v0.1.5

      with:
        host: ${{secrets.HOSTNAME}}
        key: ${{secrets.AWS_PRIVATE_KEY}}
        username: ${{ secrets.USER_NAME }}
#       Running Script

        script: |
          cd new-memories
          git pull --rebase origin master
          cd client
          npm install
          npm run build
          cd /var/www
          sudo rm -rf build
          cd
          cd new-memories/client
          sudo mv  build /var/www/build
          sudo systemctl reload nginx
          cd
          cd new-memories/server
          npm install
          kill $(lsof -t -i:5000)
          npm run start
